<?php
function biblio_citeproc_menu() {
  global $user;
  $items = array();
  $items['admin/config/content/biblio/citeproc'] = array(
    'title'             => 'CiteProc',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('biblio_citeproc_style_manager_form'),
    'access arguments'  => array('administer biblio'),
    'file'              => 'biblio_citeproc.admin.inc',
    'type'              => MENU_LOCAL_TASK,
    'weight'            => 12
  );
  $items['admin/config/content/biblio/citeproc/styles'] = array(
    'title'             => 'CiteProc Style Manager',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('biblio_citeproc_style_manager_form'),
    'access arguments'  => array('administer biblio'),
    'file'              => 'biblio_citeproc.admin.inc',
    'type'              => MENU_DEFAULT_LOCAL_TASK,
    'weight'            => 12
  );
    $items['admin/config/content/biblio/citeproc/map'] = array(
    'title'             => 'CSL Field Mapper',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('biblio_admin_io_mapper_form', 'csl', FALSE),
    'access arguments'  => array('administer biblio'),
    'file'              =>  '../../includes/biblio.admin.inc',
    'type'              => MENU_LOCAL_TASK,
    'weight'            => 12
  );
  return $items;
}
function biblio_citeproc_theme() {
  return array(
    'biblio_citeproc_style' => array(
        'function' => 'theme_biblio_citeproc_style',
        'file' => 'biblio_citeproc.module',
        'variables' => array(
          'node' => '',
          'style_name' => 'cse',
          ),
    ),
    'biblio_citeproc_style_manager_form' => array(
        'render element' => 'form',
    ),
  );
}

function biblio_citeproc_theme_registry_alter(&$theme_registry) {
  $theme_registry['biblio_style'] = $theme_registry['biblio_citeproc_style'];
}

function theme_biblio_citeproc_style($variables) {
  static $citeproc;
  global $language;
  $cached = NULL;
  $node = $variables['node'];

  module_load_include('inc', 'biblio_citeproc', 'CSL');

  if (!$citeproc) {
    $csl_id = biblio_get_style();

    $csl = db_query('SELECT parent,csl FROM {biblio_citeproc_styles} WHERE filename = :id', array(':id' => $csl_id))->fetchObject();
    if (!isset($csl->csl)) {
      drupal_set_message(t('Biblio-CiteProc could not fetch the style file: !csl_id from the database.', array('!csl_id' => $csl_id)), 'error');
      return;
    }
    if (!empty($csl->parent)) {
      $csl_file_contents = db_query("SELECT csl FROM biblio_citeproc_styles WHERE id = :id", array(':id' => $csl->parent))->fetchField();

    }
    else {
      $csl_file_contents = $csl->csl;
    }
    //    $cslid = $csl_file_name . '-' . $language->language;
//    $cached = cache_get($cslid, 'cache_biblio_csl_object');
    if (!$cached) {
      $citeproc = new citeproc($csl_file_contents, $language->language);
//      cache_set($cslid, $citeproc, 'cache_biblio_csl_object');
    }
    else {
      $citeproc = $cached->data;
    }
  }
  $styled_node = $citeproc->render($node);

  return ($styled_node . filter_xss($node->biblio_coins, array('span')));
}

function biblio_citeproc_csl_map_reset($type = NULL) {
  module_load_include('install', 'biblio_citeproc', 'biblio_citeproc');
  _reset_csl_map($type);
}
