<?php
/**
 * @file
 * Main functionality file for the biblio UI module.
 */


/**
 * Implements hook_menu().
 */
function biblio_ui_menu() {
  $items = array();

  $items['admin/content/biblio'] = array(
    'title' => 'Biblio',
    'description' => 'Manage all the biblio content on your site.',
    'access arguments' => array('administer biblio'),
    'page callback' => 'biblio_ui_manage',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/biblio'] = array(
    'title' => 'Biblio',
    'description' => 'Manage biblio',
    'access arguments' => array('administer biblio'),
  );

  $items['admin/biblio/add'] = array(
    'title' => 'Add biblio entries',
    'description' => 'Select a biblio type to create an entry for.',
    'access arguments' => array('create biblio'),
    'type' => MENU_LOCAL_ACTION,
  );

  $types = array(
    'book' => array(
      'title' => t('Book'),
    ),
  );

  foreach ($types as $type => $info) {
    $items['admin/biblio/add/' . $type] = array(
      'title' => $info['title'],
      'description' => 'Create biblio entries.',
      'access arguments' => array('create biblio'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('biblio_ui_manage_biblio', $type),
    );
  }

  $items['biblio/%biblio'] = array(
    'title' => 'View',
    'access arguments' => array('view biblio'),
    'page callback' => 'biblio_ui_view_biblio',
  );

  $items['biblio/%biblio/view'] = array(
    'title' => 'View',
    'access arguments' => array('view biblio'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('biblio_ui_manage_biblio', 1),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => '50',
  );

  $items['biblio/%biblio/edit'] = array(
    'title' => 'Edit',
    'description callback' => 'biblio_ui_description_callback',
    'description arguments' => array(1, 'edit'),
    'access arguments' => array('edit biblio'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('biblio_ui_manage_biblio', 1),
    'type' => MENU_LOCAL_TASK,
    'weight' => '60',
  );

  $items['biblio/%biblio/delete'] = array(
    'title' => 'Delete',
    'description callback' => 'biblio_ui_description_callback',
    'description arguments' => array(1, 'delete'),
    'access arguments' => array('delete biblio'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('biblio_ui_delete_biblio', 1),
    'type' => MENU_LOCAL_TASK,
    'weight' => '70',
  );

  $items['admin/structure/biblio'] = array(
    'title' => 'Biblio types',
    'description' => 'Manage biblio types',
    'access arguments' => array('administer biblio'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('biblio_ui_manage_bundles'),
  );

  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function biblio_ui_admin_paths() {
  return array(
    'biblio/*/edit' => TRUE,
    'biblio/*/delete' => TRUE,
  );
}

/**
 * Generating a description for page when editing or deleting a biblio.
 *
 * @param $biblio
 *  The biblio object.
 * @param $action
 *  The action: delete or edit.
 *
 * @return
 *  The title which the page should present.
 */
function biblio_ui_description_callback($biblio, $action) {
  return t('@action @title', array(
    '@action' => $action == 'edit' ? 'Editing' : 'Deleting',
    '@title' => $biblio->title,
  ));
}

/**
 * Manage the biblio entries in you site.
 */
function biblio_ui_manage() {
  return 'a';
}

/**
 * Display a list of biblio types for creating an entry.
 */
function biblio_ui_add_biblio_types() {
  return l(t('Book'), 'admin/biblio/add/book');
}

/**
 * Viewing a biblio entity entry.
 */
function biblio_ui_view_biblio() {
  return 'a';
}

/**
 * Form for creating a biblio entry.
 */
function biblio_ui_manage_biblio($form, &$form_state, $type) {
  global $user;

  $account = user_load($user->uid);

  $biblio = !is_object($type) ? biblio_create($type) :  $type;

  $form_state['#entity'] = $biblio;

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#required' => TRUE,
    '#weight' => -10,
    '#default_value' => !empty($biblio->title) ? $biblio->title : '',
  );

  field_attach_form('biblio', $biblio, $form, $form_state);

  $form['additional_settings'] = array(
    '#type' => 'vertical_tabs',
    '#weight' => 99,
  );

  $form['owner'] = array(
    '#type' => 'fieldset',
    '#title' => t('Authoring information'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'additional_settings',
    '#attributes' => array(
      'class' => array('biblio-form-owner'),
    ),
    '#attached' => array(
      'js' => array(
        drupal_get_path('module', 'biblio_ui') . '/js/biblio_ui.js',
        array(
          'type' => 'setting',
          'data' => array('anonymous' => variable_get('anonymous', t('Anonymous'))),
        ),
      ),
    ),
    '#weight' => 90,
  );

  $form['owner']['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Created by'),
    '#maxlength' => 60,
    '#autocomplete_path' => 'user/autocomplete',
    '#default_value' => !empty($biblio->uid) ? user_load($biblio->uid)->name : $account->name,
    '#weight' => -1,
    '#description' => t('Leave blank for %anonymous.', array('%anonymous' => variable_get('anonymous', t('Anonymous')))),
  );

  $form['published'] = array(
    '#type' => 'fieldset',
    '#title' => t('Published'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'additional_settings',
    '#weight' => 100,
  );

  $timestamp_property = empty($biblio->is_new) ? 'changed' : 'created';

  $form['published']['created'] = array(
    '#type' => 'textfield',
    '#date_format' => 'Y-m-d G:i ',
    '#title' => t('Published time'),
    '#default_value' => date('Y-m-d H:i', $biblio->{$timestamp_property}),
  );

  $form['actions'] = array(
    '#type' => 'actions',
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Send'),
    ),
    'cancel' => array(
      '#markup' => l(t('Cancel'), 'admin/biblio/add'),
    ),
  );

  return $form;
}

/**
 * Validate the submitted biblio.
 */
function biblio_ui_manage_biblio_validate($form, &$form_state) {
  field_attach_form_validate('biblio', $form_state['#entity'], $form, $form_state);
}

/**
 * Save the form biblio.
 */
function biblio_ui_manage_biblio_submit($form, &$form_state) {
  $biblio = $form_state['#entity'];

  field_attach_submit('biblio', $biblio, $form, $form_state);

  $biblio->title = $form_state['values']['title'];

  $timestamp_property = empty($biblio->is_new) ? 'changed' : 'created';

  $biblio->{$timestamp_property} = strtotime($form_state['values']['created']);
  $biblio->uid = user_load_by_name($form_state['values']['name'])->uid;

  $biblio->save();


  $form_state['redirect'] = 'admin/content/biblio';
}
