<?php

/**
 * Implements hook_theme().
 */
function biblio_example_theme() {
  $theme['biblio_example_citeproc'] = array(
    'variables' => array(
      'id' => NULL,
      'image' => NULL,
      'citation' => NULL,
      'abstract' => NULL,
      'pdf_list' => NULL,
    ),
    'path' => drupal_get_path('module', 'biblio_example') . '/templates',
    'template' => 'biblio-example-citeproc',
  );

  return $theme;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function biblio_example_ctools_plugin_directory($module, $plugin) {
  if ($module == 'biblio') {
    return 'plugins/' . $plugin;
  }
}